### ISSUE TITLE
Roster.php

### ISSUE THREAD

**Issue by LaocheXe** [Jimmi08/jbClan#1]
It seems for the front end, the roster is only showing one user name, in the admin area I selected to display Nick Name (which I believe is User Display Name)

![capture](https://cloud.githubusercontent.com/assets/5818022/20039359/18a8722e-a408-11e6-91eb-0ac2044fbe4e.PNG)

http://clancoyote.com/main/e107_plugins/jbroster_menu/jbroster.php

Up top (Clan Coyote Leadership) shows Organization Leader just fine, however it seems that Web Admin and Organization Captain are all over (LaocheXe is Web Admin, and CYTRagman is Organization Captain), and the nick names aren't displayed, Web Admin Nick Name is Organization Leader, and Organization Captain Nick Name is Web Admin, I don't know if it is a sorting order or what.

Next is that the Grunts (Bottom) have columns but no nick names or real names.

**Comment by Jimmi08** [comment]
I didn't change these things . But real name is displayed of you insert it in manager roster.
![image](https://cloud.githubusercontent.com/assets/5429548/20039551/3763aeb6-a446-11e6-9e58-e6e03fb4d0f0.png)
![image](https://cloud.githubusercontent.com/assets/5429548/20039557/4d132cd2-a446-11e6-98bf-0eeca9b1af7e.png)

**Comment by Jimmi08** [comment]
@LaocheXe Confirmed. Problem is in user import. Did you import all your users?

**Comment by Jimmi08** [comment]
I don't understand why member_id had to be the same as user_id. You create member manually, got f.e. ID 1 and then import all users and you again get ID 1 again.

**Comment by Jimmi08** [comment]
There was mistypo in original plugin and custom values with import of all users weren't created (no nick name there).  Hopefully this is enough.
